runtime: php72
 

handlers:

- url: /animal_shop/image
  static_dir: animal_shop/image

- url: /animal_shop/js
  static_dir: animal_shop/js
  
- url: /animal_shop/css
  static_dir: animal_shop/css
  
- url: /animal_shop/plugin
  static_dir: animal_shop/plugin

- url: /backstage/image/monkeys.jpg
  static_files: animal_shop/backstage/image/monkeys.jpg
  upload: animal_shop/backstage/image/monkeys.jpg

- url: /backstage/image/elephants.jpg
  static_files: animal_shop/backstage/image/elephants.jpg
  upload: animal_shop/backstage/image/elephants.jpg

- url: /backstage/image/giraffes.jpg
  static_files: animal_shop/backstage/image/giraffes.jpg
  upload: animal_shop/backstage/image/giraffes.jpg

  
- url: /image/couglogo.jpg
  static_files: animal_shop/image/couglogo.jpg
  upload: animal_shop/image/couglogo.jpg

- url: /plugin/semantic/semantic.css
  static_files: animal_shop/plugin/semantic/semantic.css
  upload: animal_shop/plugin/semantic/semantic.css

- url: /plugin/css/layui.css
  static_files: animal_shop/plugin/css/layui.css
  upload: animal_shop/plugin/css/layui.css

  

- url: /plugin/css/
  static_files: animal_shop/plugin/css/*
  upload: animal_shop/plugin/css/layui.css

- url: /plugin/layui/layui.js
  static_files: animal_shop/plugin/layui/layui.js
  upload: animal_shop/plugin/layui/layui.js

- url: /plugin/layui/layui.all.js
  static_files: animal_shop/plugin/layui/layui.all.js
  upload: animal_shop/plugin/layui/layui.all.js

- url: /css/login.css
  static_files: animal_shop/css/login.css
  upload: animal_shop/css/login.css

- url: /js/jquery.js
  static_files: animal_shop/js/jquery.js
  upload: animal_shop/js/jquery.js

- url: /animal_shop/login.html
  static_files: animal_shop/login.html
  upload: animal_shop/login.html

- url: /animal_shop/AdminMainPage.html
  static_files: animal_shop/AdminMainPage.html
  upload: animal_shop/AdminMainPage.html

- url: /animal_shop/AccountantMainPage.html
  static_files: animal_shop/AccountantMainPage.html
  upload: animal_shop/AccountantMainPage.html
  
- url: /AccountantMainPage.html
  static_files: animal_shop/backstage/AccountantMainPage.html
  upload: animal_shop/backstage/AccountantMainPage.html

- url: /animal_shop/backstage/EmployeeRegistration.html
  static_files: animal_shop/backstage/EmployeeRegistration.html
  upload: animal_shop/backstage/EmployeeRegistration.html
  
- url: /backstage/EmployeeRegistration.html
  static_files: animal_shop/backstage/EmployeeRegistration.html
  upload: animal_shop/backstage/EmployeeRegistration.html
  
- url: /EmployeeRegistration.html
  static_files: animal_shop/backstage/EmployeeRegistration.html
  upload: animal_shop/backstage/EmployeeRegistration.html

- url: /animal_shop/ZookeeperMainPage.html
  static_files: animal_shop/ZookeeperMainPage.html
  upload: animal_shop/ZookeeperMainPage.html

- url: /animal_shop/backstage/FinancialReport.html
  static_files: animal_shop/backstage/FinancialReport.html
  upload: animal_shop/backstage/FinancialReport.html
  
- url: /animal_shop/backstage/FinancialReport.html
  static_files: animal_shop/backstage/FinancialReport.html
  upload: animal_shop/backstage/FinancialReport.html

- url: /backstage/AnimalReport.html
  static_files: animal_shop/backstage/AnimalReport.html
  upload: animal_shop/backstage/AnimalReport.html

- url: /backstage/ShopReport.html
  static_files: animal_shop/backstage/ShopReport.html
  upload: animal_shop/backstage/ShopReport.html
  
- url: /backstage/index.html
  static_files: animal_shop/backstage/index.html
  upload: animal_shop/backstage/index.html
  
- url: /
  static_files: animal_shop/login.html
  upload: animal_shop/login.html
  
- url: /animal_shop/AdminMainPage.html
  static_files: animal_shop/AdminMainPage.html
  upload: animal_shop/AdminMainPage.html
  
- url: /.*
  script: auto
