runtime: php72
 

handlers:

- url: /(.+\.(gif|png|jpg|css|js|map|PNG))$
  static_files: \1
  upload: .+\.(gif|png|jpg|css|js|map|PNG)$
  
- url: /image/jaguars-zoo.jpg
  static_files: animal_shop/image/jaguars-zoo.jpg
  upload: animal_shop/image/jaguars-zoo.jpg

- url: /
  static_files: animal_shop/login.html
  upload: animal_shop/login.html

- url: /
  static_files: animal_shop/AdminMainPage.html
  upload: animal_shop/AdminMainPage.html

- url: /
  static_files: animal_shop/AccountantMainPage.html
  upload: animal_shop/AccountantMainPage.html
  
- url: /
  static_files: AccountantMainPage.html
  upload: AccountantMainPage.html

- url: /
  static_files: animal_shop/backstage/EmployeeRegistration.html
  upload: animal_shop/backstage/EmployeeRegistration.html
  
- url: /
  static_files: backstage/EmployeeRegistration.html
  upload: backstage/EmployeeRegistration.html
  
- url: /
  static_files: EmployeeRegistration.html
  upload: EmployeeRegistration.html

- url: /
  static_files: animal_shop/ZookeeperMainPage.html
  upload: animal_shop/ZookeeperMainPage.html

- url: /
  static_files: animal_shop/backstage/FinancialReport.html
  upload: animal_shop/backstage/FinancialReport.html
  
- url: /
  static_files: backstage/FinancialReport.html
  upload: backstage/FinancialReport.html

- url: /
  static_files: backstage/AnimalReport.html
  upload: backstage/AnimalReport.html

- url: /
  static_files: backstage/ShopReport.html
  upload: backstage/ShopReport.html
  
- url: /
  static_files: backstage/index.html
  upload: backstage/index.html
  
- url: /.*
  script: auto
